#ifndef RT_CONFIG_H__
#define RT_CONFIG_H__

#define RT_USING_NANO
#define RT_NAME_MAX 24
#define RT_CPUS_NR 1
#define RT_ALIGN_SIZE 8
#define RT_THREAD_PRIORITY_32
#define RT_THREAD_PRIORITY_MAX 32
#define RT_TICK_PER_SECOND 100
#define IDLE_THREAD_STACK_SIZE 4096

#define RT_USING_SEMAPHORE
#define RT_USING_MUTEX

#define RT_USING_SMALL_MEM
#define RT_USING_SMALL_MEM_AS_HEAP
#define RT_USING_HEAP

#define RT_USING_CONSOLE
#define RT_CONSOLEBUF_SIZE 256
#define RT_VER_NUM 0x50300
#define RT_BACKTRACE_LEVEL_MAX_NR 16

#define ARCH_CPU_64BIT
#define RT_USING_CACHE
#define ARCH_RISCV
#define ARCH_RISCV64
#define ARCH_USING_NEW_CTX_SWITCH
#define ARCH_USING_RISCV_COMMON64
#define CLOCK_TIMER_FREQ 10000000
#define __STACKSIZE__ 16384

#define RT_USING_COMPONENTS_INIT
#define RT_USING_USER_MAIN
#define RT_MAIN_THREAD_STACK_SIZE 8192
#define RT_MAIN_THREAD_PRIORITY 10

#endif
