#!/usr/bin/env python3
"""Convert Doxygen XML groups into GitHub Wiki Markdown pages."""

from __future__ import annotations

import argparse
import copy
import re
import shutil
import xml.etree.ElementTree as ET
from pathlib import Path


GENERATED_MANIFEST = ".hazel-osal-generated-pages"


def text(node: ET.Element | None) -> str:
    """Return normalized visible text from a Doxygen XML node."""
    if node is None:
        return ""
    return " ".join("".join(node.itertext()).split())


def slug(value: str) -> str:
    value = re.sub(r"[^A-Za-z0-9]+", "-", value).strip("-")
    return value or "Reference"


def description(node: ET.Element, tag: str) -> str:
    source = node.find(tag)
    if source is None:
        return ""
    filtered = copy.deepcopy(source)
    for parent in filtered.iter():
        for child in list(parent):
            if child.tag in {"parameterlist", "simplesect"}:
                parent.remove(child)
    return text(filtered)


def render_parameters(member: ET.Element) -> list[str]:
    rows: list[str] = []
    for item in member.findall(
        ".//parameterlist[@kind='param']/parameteritem"
    ):
        names = [
            text(name)
            for name in item.findall("./parameternamelist/parametername")
        ]
        detail = text(item.find("parameterdescription"))
        rows.append(f"- `{', '.join(names)}`: {detail or 'No description.'}")
    return rows


def render_member(member: ET.Element) -> list[str]:
    name = text(member.find("name"))
    kind = member.get("kind", "member")
    lines = [f"### `{name}`", ""]

    definition = text(member.find("definition"))
    args = text(member.find("argsstring"))
    initializer = text(member.find("initializer"))
    signature = f"{definition}{args}".strip()
    if initializer:
        signature = f"{signature} {initializer}".strip()
    if signature:
        lines.extend(["```c", signature, "```", ""])

    brief = description(member, "briefdescription")
    detail = description(member, "detaileddescription")
    if brief:
        lines.extend([brief, ""])
    if detail and detail != brief:
        lines.extend([detail, ""])

    params = render_parameters(member)
    if params:
        lines.extend(["Parameters:", "", *params, ""])

    returns = [
        text(section)
        for section in member.findall(".//simplesect[@kind='return']")
        if text(section)
    ]
    if returns:
        lines.extend([f"Returns: {' '.join(returns)}", ""])

    if kind == "enum":
        values = []
        for value in member.findall("enumvalue"):
            enum_name = text(value.find("name"))
            enum_desc = description(value, "briefdescription") or description(
                value, "detaileddescription"
            )
            values.append(f"- `{enum_name}`: {enum_desc or 'No description.'}")
        if values:
            lines.extend(["Values:", "", *values, ""])

    return lines


def render_group(xml_path: Path) -> tuple[str, str]:
    compound = ET.parse(xml_path).getroot().find("compounddef")
    if compound is None:
        raise ValueError(f"No compound definition in {xml_path}")

    title = text(compound.find("title")) or text(compound.find("compoundname"))
    lines = [f"# {title}", "", "<!-- Generated by scripts/doxygen-to-wiki.py. -->", ""]
    brief = description(compound, "briefdescription")
    detail = description(compound, "detaileddescription")
    if brief:
        lines.extend([brief, ""])
    if detail and detail != brief:
        lines.extend([detail, ""])

    for section in compound.findall("sectiondef"):
        section_title = text(section.find("header"))
        if section_title:
            lines.extend([f"## {section_title}", ""])
        for member in section.findall("memberdef"):
            lines.extend(render_member(member))

    return title, "\n".join(lines).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--xml", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--repository", required=True)
    parser.add_argument("--source-sha", required=True)
    args = parser.parse_args()

    index_path = args.xml / "index.xml"
    if not index_path.is_file():
        parser.error(f"Doxygen index not found: {index_path}")

    if args.output.exists():
        shutil.rmtree(args.output)
    args.output.mkdir(parents=True)

    groups: list[tuple[str, str]] = []
    index = ET.parse(index_path).getroot()
    for entry in index.findall("compound[@kind='group']"):
        refid = entry.get("refid")
        if not refid:
            continue
        title, markdown = render_group(args.xml / f"{refid}.xml")
        filename = f"API-{slug(title)}.md"
        (args.output / filename).write_text(markdown, encoding="utf-8")
        groups.append((title, filename))

    if not groups:
        parser.error("Doxygen XML contains no documented API groups")
    groups.sort(key=lambda item: item[0].casefold())

    short_sha = args.source_sha[:12]
    source_url = f"https://github.com/{args.repository}/commit/{args.source_sha}"
    links = [f"- [[{title}|{Path(filename).stem}]]" for title, filename in groups]
    home = [
        "# Hazel OSAL",
        "",
        "Portable OS abstraction layer for FreeRTOS, RT-Thread, and Zephyr,",
        "with QEMU tests for RISC-V and ARM.",
        "",
        "This API reference is generated from the Doxygen comments on every",
        "push to `main`.",
        "",
        f"Source: [`{short_sha}`]({source_url})",
        "",
        "## API reference",
        "",
        *links,
        "",
    ]
    (args.output / "Home.md").write_text("\n".join(home), encoding="utf-8")
    sidebar = ["## Hazel OSAL", "", "- [[Home]]", *links, ""]
    (args.output / "_Sidebar.md").write_text(
        "\n".join(sidebar), encoding="utf-8"
    )

    generated = ["Home.md", "_Sidebar.md", *(name for _, name in groups)]
    (args.output / GENERATED_MANIFEST).write_text(
        "\n".join(generated) + "\n", encoding="utf-8"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
